import 'dart:convert';
import 'package:http/http.dart' as http;
import '../config/api_config.dart';

/// Question generated by AI with answer explanation.
class AiQuestion {
  final String subject;
  final String question;
  final List<String> options;
  final int correctIndex;
  final String explanation; // Why the correct answer is right

  const AiQuestion({
    required this.subject,
    required this.question,
    required this.options,
    required this.correctIndex,
    required this.explanation,
  });

  factory AiQuestion.fromJson(Map<String, dynamic> json) {
    return AiQuestion(
      subject: json['subject'] ?? '',
      question: json['question'] ?? '',
      options: List<String>.from(json['options'] ?? []),
      correctIndex: json['correctIndex'] ?? 0,
      explanation: json['explanation'] ?? '',
    );
  }
}

/// Result of the AI evaluation.
class EvaluationResult {
  final int totalQuestions;
  final int correctAnswers;
  final double percentage;
  final String level; // Beginner, Intermediate, Advanced
  final String summary;
  final Map<String, double> subjectScores; // subject name → score 0-1

  const EvaluationResult({
    required this.totalQuestions,
    required this.correctAnswers,
    required this.percentage,
    required this.level,
    required this.summary,
    required this.subjectScores,
  });
}

/// Service for AI-powered quiz generation and evaluation via OpenRouter.
class AiService {
  /// Generate quiz questions for the given subjects (5 per subject).
  Future<List<AiQuestion>> generateQuiz(List<String> subjectNames) async {
    final subjectList = subjectNames.join(', ');
    final totalQ = subjectNames.length * 5;

    final prompt = '''
You are an Informatics education expert. Generate a diagnostic quiz to assess a student's level.

Subjects to test: $subjectList
Generate exactly 5 multiple-choice questions PER subject ($totalQ total).

For each question provide:
- subject: the subject area
- question: clear question text
- options: exactly 4 answer choices (array of strings)
- correctIndex: index (0-3) of the correct answer
- explanation: 1-2 sentence explanation of why the correct answer is right and why common wrong answers are wrong

Mix difficulty levels: 2 easy, 2 medium, 1 hard per subject.

Return ONLY a valid JSON array, no markdown, no code fences:
[{"subject":"...","question":"...","options":["A","B","C","D"],"correctIndex":0,"explanation":"..."}]
''';

    try {
      final response = await http.post(
        Uri.parse(ApiConfig.openRouterUrl),
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ${ApiConfig.openRouterApiKey}',
        },
        body: jsonEncode({
          'model': ApiConfig.model,
          'messages': [
            {'role': 'user', 'content': prompt},
          ],
          'temperature': 0.7,
          'max_tokens': 4000,
        }),
      );

      if (response.statusCode != 200) {
        throw Exception('API error: ${response.statusCode} ${response.body}');
      }

      final data = jsonDecode(response.body);
      final content = data['choices'][0]['message']['content'] as String;

      // Parse the JSON from the response (strip any markdown fences)
      String cleaned = content.trim();
      if (cleaned.startsWith('```')) {
        cleaned = cleaned.replaceAll(RegExp(r'^```\w*\n?'), '').replaceAll(RegExp(r'\n?```$'), '');
      }

      final List<dynamic> parsed = jsonDecode(cleaned);
      return parsed.map((q) => AiQuestion.fromJson(q as Map<String, dynamic>)).toList();
    } catch (e) {
      // Fallback: return hardcoded questions if API fails
      return _fallbackQuestions(subjectNames);
    }
  }

  /// Evaluate the quiz results and determine student level.
  EvaluationResult evaluateResults({
    required List<AiQuestion> questions,
    required Map<int, int> answers,
    required List<String> subjectNames,
  }) {
    int correct = 0;
    final Map<String, int> subjectCorrect = {};
    final Map<String, int> subjectTotal = {};

    for (int i = 0; i < questions.length; i++) {
      final q = questions[i];
      subjectTotal[q.subject] = (subjectTotal[q.subject] ?? 0) + 1;

      if (answers[i] == q.correctIndex) {
        correct++;
        subjectCorrect[q.subject] = (subjectCorrect[q.subject] ?? 0) + 1;
      }
    }

    final pct = questions.isEmpty ? 0.0 : correct / questions.length;
    final String level;
    final String summary;

    if (pct >= 0.8) {
      level = 'Advanced';
      summary = 'Excellent! You have a strong foundation in these subjects. '
          'We\'ll focus on advanced topics and challenging exercises.';
    } else if (pct >= 0.5) {
      level = 'Intermediate';
      summary = 'Good progress! You have solid basics but room to grow. '
          'We\'ll strengthen weak areas while introducing new concepts.';
    } else {
      level = 'Beginner';
      summary = 'Great starting point! We\'ll build your knowledge from the ground up '
          'with structured lessons tailored to your pace.';
    }

    final Map<String, double> subjectScores = {};
    for (final name in subjectNames) {
      final total = subjectTotal[name] ?? 1;
      final right = subjectCorrect[name] ?? 0;
      subjectScores[name] = right / total;
    }

    return EvaluationResult(
      totalQuestions: questions.length,
      correctAnswers: correct,
      percentage: pct,
      level: level,
      summary: summary,
      subjectScores: subjectScores,
    );
  }

  /// Fallback questions if the API fails.
  List<AiQuestion> _fallbackQuestions(List<String> subjects) {
    final List<AiQuestion> result = [];
    final fallback = {
      'Programming Basics': [
        AiQuestion(subject: 'Programming Basics', question: 'What is a variable?', options: ['A loop construct', 'A named storage location in memory', 'A type of function', 'A compilation error'], correctIndex: 1, explanation: 'A variable is a named storage location that holds a value which can change during program execution.'),
        AiQuestion(subject: 'Programming Basics', question: 'Which keyword is used to define a function in Python?', options: ['func', 'function', 'def', 'define'], correctIndex: 2, explanation: 'Python uses the "def" keyword to define functions, followed by the function name and parentheses.'),
        AiQuestion(subject: 'Programming Basics', question: 'What does OOP stand for?', options: ['Object-Oriented Programming', 'Open Operating Protocol', 'Ordered Output Process', 'Optional Object Parameters'], correctIndex: 0, explanation: 'OOP stands for Object-Oriented Programming, a paradigm based on objects containing data and methods.'),
        AiQuestion(subject: 'Programming Basics', question: 'What is the output of: print(type(42))?', options: ['<class \'str\'>', '<class \'int\'>', '<class \'float\'>', 'Error'], correctIndex: 1, explanation: '42 is an integer literal in Python, so type(42) returns <class \'int\'>.'),
        AiQuestion(subject: 'Programming Basics', question: 'Which loop runs at least once?', options: ['for loop', 'while loop', 'do-while loop', 'foreach loop'], correctIndex: 2, explanation: 'A do-while loop checks the condition after executing the body, guaranteeing at least one execution.'),
      ],
      'Algorithms': [
        AiQuestion(subject: 'Algorithms', question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correctIndex: 1, explanation: 'Binary search halves the search space each step, giving O(log n) time complexity.'),
        AiQuestion(subject: 'Algorithms', question: 'Which sorting algorithm has O(n log n) average case?', options: ['Bubble Sort', 'Selection Sort', 'Merge Sort', 'Insertion Sort'], correctIndex: 2, explanation: 'Merge Sort divides the array in half recursively and merges in linear time, giving O(n log n).'),
        AiQuestion(subject: 'Algorithms', question: 'What is recursion?', options: ['A loop that runs forever', 'A function that calls itself', 'A type of data structure', 'An optimization technique'], correctIndex: 1, explanation: 'Recursion is when a function calls itself with a smaller input, moving toward a base case.'),
        AiQuestion(subject: 'Algorithms', question: 'What does Big-O notation measure?', options: ['Exact runtime', 'Memory usage only', 'Upper bound of growth rate', 'Code quality'], correctIndex: 2, explanation: 'Big-O describes the upper bound of an algorithm\'s growth rate as input size increases.'),
        AiQuestion(subject: 'Algorithms', question: 'Which technique does quicksort use?', options: ['Dynamic programming', 'Divide and conquer', 'Greedy approach', 'Backtracking'], correctIndex: 1, explanation: 'Quicksort uses divide and conquer by partitioning around a pivot element.'),
      ],
      'Data Structures': [
        AiQuestion(subject: 'Data Structures', question: 'Which data structure uses FIFO ordering?', options: ['Stack', 'Queue', 'Tree', 'Graph'], correctIndex: 1, explanation: 'A Queue follows First-In-First-Out: the first element added is the first removed.'),
        AiQuestion(subject: 'Data Structures', question: 'What is the time complexity of accessing an array element by index?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correctIndex: 3, explanation: 'Arrays provide O(1) direct access because elements are stored in contiguous memory.'),
        AiQuestion(subject: 'Data Structures', question: 'Which structure uses LIFO?', options: ['Queue', 'Stack', 'Linked List', 'Hash Table'], correctIndex: 1, explanation: 'A Stack follows Last-In-First-Out: the most recently added element is removed first.'),
        AiQuestion(subject: 'Data Structures', question: 'What is a binary tree?', options: ['A tree with max 2 children per node', 'A tree with exactly 2 nodes', 'A sorted array', 'A type of graph'], correctIndex: 0, explanation: 'A binary tree is a tree where each node has at most two children (left and right).'),
        AiQuestion(subject: 'Data Structures', question: 'What is the purpose of a hash table?', options: ['Sorting data', 'Fast key-value lookup', 'Hierarchical storage', 'Sequential access'], correctIndex: 1, explanation: 'Hash tables provide O(1) average-case lookups by mapping keys to array indices via a hash function.'),
      ],
      'Databases': [
        AiQuestion(subject: 'Databases', question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Standard Question Language', 'Sequential Query Lookup'], correctIndex: 0, explanation: 'SQL stands for Structured Query Language, used to manage relational databases.'),
        AiQuestion(subject: 'Databases', question: 'Which SQL command retrieves data?', options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], correctIndex: 2, explanation: 'SELECT is used to query and retrieve data from database tables.'),
        AiQuestion(subject: 'Databases', question: 'What is a primary key?', options: ['Any column', 'A unique identifier for each row', 'A foreign reference', 'An index type'], correctIndex: 1, explanation: 'A primary key uniquely identifies each record in a table and cannot contain NULL values.'),
        AiQuestion(subject: 'Databases', question: 'What is normalization?', options: ['Making data bigger', 'Organizing data to reduce redundancy', 'Encrypting data', 'Backing up data'], correctIndex: 1, explanation: 'Normalization organizes database tables to minimize redundancy and dependency issues.'),
        AiQuestion(subject: 'Databases', question: 'Which JOIN returns only matching rows from both tables?', options: ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN'], correctIndex: 2, explanation: 'INNER JOIN returns only rows where the join condition is met in both tables.'),
      ],
      'Web Basics': [
        AiQuestion(subject: 'Web Basics', question: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Logic', 'Home Tool Markup Language'], correctIndex: 0, explanation: 'HTML stands for HyperText Markup Language, the standard language for creating web pages.'),
        AiQuestion(subject: 'Web Basics', question: 'Which CSS property changes text color?', options: ['font-color', 'text-color', 'color', 'foreground'], correctIndex: 2, explanation: 'The CSS "color" property sets the text color of an element.'),
        AiQuestion(subject: 'Web Basics', question: 'What is the purpose of JavaScript?', options: ['Styling pages', 'Structuring content', 'Adding interactivity', 'Serving files'], correctIndex: 2, explanation: 'JavaScript adds interactivity and dynamic behavior to web pages.'),
        AiQuestion(subject: 'Web Basics', question: 'What HTTP method is used to submit form data?', options: ['GET', 'POST', 'PUT', 'HEAD'], correctIndex: 1, explanation: 'POST sends data to the server in the request body, commonly used for form submissions.'),
        AiQuestion(subject: 'Web Basics', question: 'What does responsive design mean?', options: ['Fast loading', 'Adapts to different screen sizes', 'Uses animations', 'Server-side rendering'], correctIndex: 1, explanation: 'Responsive design means the layout adapts to different screen sizes and devices.'),
      ],
    };

    for (final s in subjects) {
      if (fallback.containsKey(s)) {
        result.addAll(fallback[s]!);
      }
    }
    return result;
  }
}
