import 'dart:convert';
import 'package:http/http.dart' as http;
import '../config/api_config.dart';

/// Question generated by AI with answer explanation.
class AiQuestion {
  final String subject;
  final String question;
  final List<String> options;
  final int correctIndex;
  final String explanation; // Why the correct answer is right

  const AiQuestion({
    required this.subject,
    required this.question,
    required this.options,
    required this.correctIndex,
    required this.explanation,
  });

  factory AiQuestion.fromJson(Map<String, dynamic> json) {
    return AiQuestion(
      subject: json['subject'] ?? '',
      question: json['question'] ?? '',
      options: List<String>.from(json['options'] ?? []),
      correctIndex: json['correctIndex'] ?? 0,
      explanation: json['explanation'] ?? '',
    );
  }
}

/// Result of the AI evaluation.
class EvaluationResult {
  final int totalQuestions;
  final int correctAnswers;
  final double percentage;
  final String level; // Beginner, Intermediate, Advanced
  final String summary;
  final Map<String, double> subjectScores; // subject name → score 0-1

  const EvaluationResult({
    required this.totalQuestions,
    required this.correctAnswers,
    required this.percentage,
    required this.level,
    required this.summary,
    required this.subjectScores,
  });
}

/// Service for AI-powered quiz generation and evaluation via OpenRouter.
class AiService {
  /// Generate quiz questions for the given subjects (5 per subject).
  Future<List<AiQuestion>> generateQuiz(List<String> subjectNames) async {
    if (subjectNames.isEmpty) return const [];
    

    final subjectList = subjectNames.join(', ');
    final totalQ = subjectNames.length * 5;

    final prompt = '''
You are an Informatics education expert. Generate a diagnostic quiz to assess a student's level.

Subjects to test: $subjectList
Generate exactly 5 multiple-choice questions PER subject ($totalQ total).

For each question provide:
- subject: the subject area
- question: clear question text
- options: exactly 4 answer choices (array of strings)
- correctIndex: index (0-3) of the correct answer
- explanation: 1-2 sentence explanation of why the correct answer is right and why common wrong answers are wrong

Mix difficulty levels: 2 easy, 2 medium, 1 hard per subject.

Important constraints:
- Use ONLY these exact subject names: $subjectList
- Every question subject must match one of these names exactly.

Return ONLY a valid JSON array, no markdown, no code fences:
[{"subject":"...","question":"...","options":["A","B","C","D"],"correctIndex":0,"explanation":"..."}]
''';

    final response = await http.post(
      Uri.parse(ApiConfig.openRouterUrl),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ${ApiConfig.openRouterApiKey}',
        'HTTP-Referer': 'https://arsii.local',
        'X-Title': 'Arsii Evaluation Quiz',
      },
      body: jsonEncode({
        'model': ApiConfig.model,
        'messages': [
          {'role': 'user', 'content': prompt},
        ],
        'temperature': 0.7,
        'max_tokens': 4000,
      }),
    );

    if (response.statusCode != 200) {
      String message = 'OpenRouter request failed (${response.statusCode}).';
      try {
        final err = jsonDecode(response.body) as Map<String, dynamic>;
        final apiMessage = err['error']?['message'] as String?;
        if (apiMessage != null && apiMessage.trim().isNotEmpty) {
          message = apiMessage;
        }
      } catch (_) {
        // Keep generic message if response body is not valid JSON.
      }

      if (response.statusCode == 401) {
        throw Exception(
          'OpenRouter authentication failed: $message. Your API key is invalid, revoked, or belongs to a missing account.',
        );
      }

      throw Exception(message);
    }

      final data = jsonDecode(response.body);
      final content = data['choices']?[0]?['message']?['content'] as String?;
      if (content == null || content.trim().isEmpty) {
        throw const FormatException('OpenRouter returned an empty response.');
      }

      String cleaned = content.trim();
      if (cleaned.startsWith('```')) {
        cleaned = cleaned
            .replaceAll(RegExp(r'^```\w*\n?'), '')
            .replaceAll(RegExp(r'\n?```$'), '')
            .trim();
      }

      // Some models prepend explanatory text; extract the first JSON array payload.
      final jsonPayload = _extractFirstJsonArray(cleaned);
      final List<dynamic> parsed = jsonDecode(jsonPayload);

      final questions = parsed
          .map((q) => AiQuestion.fromJson(q as Map<String, dynamic>))
          .where((q) =>
              q.question.trim().isNotEmpty &&
              q.options.length == 4 &&
              q.correctIndex >= 0 &&
              q.correctIndex < 4 &&
              subjectNames.contains(q.subject))
          .toList();

      if (questions.isEmpty) {
        throw const FormatException('No valid subject-based questions were returned.');
      }

    return questions;
  }

  String _extractFirstJsonArray(String input) {
    final start = input.indexOf('[');
    if (start == -1) {
      throw const FormatException('Missing JSON array start.');
    }

    int depth = 0;
    for (int i = start; i < input.length; i++) {
      final ch = input[i];
      if (ch == '[') depth++;
      if (ch == ']') {
        depth--;
        if (depth == 0) {
          return input.substring(start, i + 1);
        }
      }
    }
    throw const FormatException('Missing JSON array end.');
  }

  /// Evaluate the quiz results and determine student level.
  EvaluationResult evaluateResults({
    required List<AiQuestion> questions,
    required Map<int, int> answers,
    required List<String> subjectNames,
  }) {
    int correct = 0;
    final Map<String, int> subjectCorrect = {};
    final Map<String, int> subjectTotal = {};

    for (int i = 0; i < questions.length; i++) {
      final q = questions[i];
      subjectTotal[q.subject] = (subjectTotal[q.subject] ?? 0) + 1;

      if (answers[i] == q.correctIndex) {
        correct++;
        subjectCorrect[q.subject] = (subjectCorrect[q.subject] ?? 0) + 1;
      }
    }

    final pct = questions.isEmpty ? 0.0 : correct / questions.length;
    final String level;
    final String summary;

    if (pct >= 0.8) {
      level = 'Advanced';
      summary = 'Excellent! You have a strong foundation in these subjects. '
          'We\'ll focus on advanced topics and challenging exercises.';
    } else if (pct >= 0.5) {
      level = 'Intermediate';
      summary = 'Good progress! You have solid basics but room to grow. '
          'We\'ll strengthen weak areas while introducing new concepts.';
    } else {
      level = 'Beginner';
      summary = 'Great starting point! We\'ll build your knowledge from the ground up '
          'with structured lessons tailored to your pace.';
    }

    final Map<String, double> subjectScores = {};
    for (final name in subjectNames) {
      final total = subjectTotal[name] ?? 1;
      final right = subjectCorrect[name] ?? 0;
      subjectScores[name] = right / total;
    }

    return EvaluationResult(
      totalQuestions: questions.length,
      correctAnswers: correct,
      percentage: pct,
      level: level,
      summary: summary,
      subjectScores: subjectScores,
    );
  }

}
